
@echo off
echo Installing Olym AI Web Browser for Windows 10/11 (x64 / ARM64)...
echo Destination: %LOCALAPPDATA%\OlymBrowser
mkdir "%LOCALAPPDATA%\OlymBrowser" 2>nul

echo Copying Chromium CDP Runtime and Olym Browser Executable...
echo Done! Creating Desktop Shortcut...
echo Launching Olym Browser...
start "" "http://localhost:3001/olym"
